### ISSUE TITLE
QXcbConnection: Could not connect to display

### ISSUE THREAD

**Issue by juandm** [apazga/docker-pgmodeler#2]
Hi there, 

I downloaded the image and tried to run it using the `sh` script replacing the `192.168.0.100:0.0` ip by my local ip, but is raising the following error:

> QXcbConnection: Could not connect to display <<"my-ip-address">>

Can you give some hint?

**Comment by apazga** [comment]
Hi! 
Your X server (or config) is missing.
Please, provide more info.
You are using Linux or Windows (which bash terminal?)?

**Comment by juandm** [comment]
Hi, I'm using `ubuntu 18.04 LTS` and `zsh` as shell.

**Comment by apazga** [comment]
Did you leave `:0.0` after your ip address? 0.0 is the display to use in your X server.

**Comment by juandm** [comment]
Yes, i only changed the ip address.

**Comment by apazga** [comment]
Did you try to run any other X11 app from the terminal? Like `xeyes`, to see if you can run X11 apps from terminal

**Comment by d4n13lbc** [comment]
This command works from me:

```
xhost +
docker run -ti --device /dev/snd -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY -v $(pwd)/data:/data apazga/docker-pgmodeler:0.9.2
```

**Comment by apazga** [comment]
It should probably work too using:
```
xhost +
docker run -ti -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY -v $(pwd)/data:/data apazga/docker-pgmodeler:0.9.2
xhost -
```

Because you don't need the sound device (--device /dev/snd) for this.

And if you use `xhost +`, it's recommended to use `xhost -` at the end too.

> If it works for you , you might consider to add it to the README.md

Thanks, I will add it too at Linux section.

**Comment by dekiesel** [comment]
Just wanted to say that the script didn't work for me on ubuntu 22.04 out of the box, but the proposed fix here worked immediately.
