### ISSUE TITLE
General.conf :unable to write the file

### ISSUE THREAD

**Issue by Asphaltio** [apazga/docker-pgmodeler#5]
Hello,

I have successfully downloaded and run the docker image for pgModeler, but I am encountering an error when saving the settings. The error message reads: "Unable to write the file /root/.config/pgmodeler-1.0/general.conf due to one or more errors in the definition generation process."
I don't know if the last 2 error is linked to my problem.

Thank you in advance.
![error-pgmodeler](https://user-images.githubusercontent.com/121285930/209304287-8b1db345-3d6f-4a3e-bd6e-b905021af5e2.png)

**Comment by Asphaltio** [comment]
Hi,
At first, the docker doesn't work with the last image, but after some time of running the container, if you connect with a bash and launch pgmodeler with the command "pgmodeler", pgmodeler working fine.
So I made an image based on my container and he is working perfectly.

Sorry for the inconvenience and thank you for this docker.

**Comment by apazga** [comment]
Hi!
No problem, thank you.
If you think something could be improved, do not hesitate to make a pull request.
Best!
